lavalink:
    plugins:
    -   dependency: com.github.TopiSenpai.LavaSrc:lavasrc-plugin:85b39d1
        repository: https://maven.topi.wtf/snapshots
    -   dependency: com.github.topisenpai:sponsorblock-plugin:2.0.0
        repository: https://jitpack.io
    -   dependency: com.dunctebot:skybot-lavalink-plugin:1.4.1
        repository: https://m2.duncte123.dev/releases
    -   dependency: me.rohank05:lavalink-filter-plugin:0.0.1
        repository: https://jitpack.io
    -   dependency: com.github.esmBot:lava-xm-plugin:v0.2.1
        repository: https://jitpack.io
    server:
        password: youshallnotpass
        bufferDurationMs: 400 # The duration of the NAS buffer. Higher values fare better against longer GC pauses. Duration <= 0 to disable JDA-NAS. Minimum of 40ms, lower values may introduce pauses.
        frameBufferDurationMs: 1000 # How many milliseconds of audio to keep buffered
        opusEncodingQuality: 10 # Opus encoder quality. Valid values range from 0 to 10, where 10 is best quality but is the most expensive on the CPU.
        playerUpdateInterval: 5 # How frequently to send player updates to clients, in seconds
        resamplingQuality: MEDIUM # Quality of resampling operations. Valid values are LOW, MEDIUM and HIGH, where HIGH uses the most CPU.
        trackStuckThresholdMs: 10000 # The threshold for how long a track can be stuck. A track is stuck if does not return any audio data.
        useSeekGhosting: true # Seek ghosting is the effect where whilst a seek is in progress, the audio buffer is read from until empty, or until seek is ready.
        youtubePlaylistLoadLimit: 6 # Number of pages at 100 each
        youtubeSearchEnabled: true # Whether to enable youtube search
        soundcloudSearchEnabled: true # Whether to enable soundcloud search
        gc-warnings: true
        sources:
            bandcamp: true
            http: true
            local: true
            soundcloud: true
            twitch: true
            vimeo: true
            youtube: true
        filters: # All filters are enabled by default
            volume: true
            equalizer: true
            karaoke: true
            timescale: true
            tremolo: true
            vibrato: true
            distortion: true
            rotation: true
            channelMix: true
            lowPass: true
            echo: true # From lavalink-filter-plugin
#    ratelimit:
#        ipBlocks: [1.0.0.0/8, '...'] # list of ip blocks
#        excludedIps: ['...', '...'] # ips which should be explicit excluded from usage by lavalink
#        strategy: RotateOnBan # RotateOnBan | LoadBalance | NanoSwitch | RotatingNanoSwitch
#        searchTriggersFail: true # Whether a search 429 should trigger marking the ip as failing
#        retryLimit: -1 # -1 = use default lavaplayer value | 0 = infinity | >0 = retry will happen this numbers times
#    youtubeConfig: # Required for avoiding all age restrictions by YouTube, some restricted videos still can be played without.
#        email: '' # Email of Google account
#        password: '' # Password of Google account
#    httpConfig: # Useful for blocking bad-actors from ip-grabbing your music node and attacking it, this way only the http proxy will be attacked
#        proxyHost: localhost # Hostname of the proxy, (ip or domain)
#        proxyPort: 3128 # Proxy port, 3128 is the default for squidProxy
#        proxyUser: '' # Optional user for basic authentication fields, leave blank if you don't use basic auth
#        proxyPassword: '' # Password for basic authentication
plugins:
    dunctebot:
        sources:
            getyarn: true # www.getyarn.io
            clypit: true # www.clyp.it
            tts: true # speak:Words to speak
            pornhub: true # should be self-explanatory
            reddit: true # should be self-explanatory
            ocremix: true # www.ocremix.org
            tiktok: true # tiktok.com
            mixcloud: true # mixcloud.com
            soundgasm: true # soundgasm.net
        ttsLanguage: en-US # language of the TTS engine
    lavasrc:
        sources:
            spotify: true # Enable Spotify source
            applemusic: true # Enable Apple Music source
            deezer: true # Enable Deezer source
            yandexmusic: false # Enable Yandex Music source
        providers:
        -   dzisrc:%ISRC% # Deezer ISRC Search
        -   ytmsearch:"%ISRC%" # YouTube Music ISRC Search
        -   ytsearch:"%ISRC%" # YouTube ISRC Search
        -   dzsearch:%QUERY% # Deezer Search
        -   ytmsearch:%QUERY% # YouTube Music Search
        -   ytsearch:%QUERY% # YouTube Search
        -   scsearch:%QUERY% # SoundCloud Search
        applemusic:
            countryCode: US # the country code you want to use for filtering the artists top tracks and language. See https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
            #mediaAPIToken: CHANGE_ME # Can be used to bypass the auto token fetching which is likely to break again in the future
            playlistLoadLimit: 6 # The number of pages at 300 tracks each
            albumLoadLimit: 6 # The number of pages at 300 tracks each
        spotify:
            clientId: CHANGE_ME
            clientSecret: CHANGE_ME
            countryCode: US # the country code you want to use for filtering the artists top tracks. See https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
            playlistLoadLimit: 6 # The number of pages at 100 tracks each
            albumLoadLimit: 6 # The number of pages at 50 tracks each
        deezer:
            masterDecryptionKey: CHANGE_ME # the master key used for decrypting the deezer tracks. (yes this is not here you need to get it from somewhere else)
            # P.S IT IS NOT id58zow5hmqhdv24zil4znth3ywy8prt9-dizzzrlba8q4h2al0ywmhp2zg-1d5g
#        yandexmusic:
#            accessToken: CHANGE_ME # the token used for accessing the yandex music api. See https://github.com/TopiSenpai/LavaSrc#yandex-music
server:
    address: localhost # Address to bind the server to, Client will connect to this address - 0.0.0.0 means all addresses, if you are using the node on same machine as bot then use localhost
    port: 2154 # Port to run the server on, Client will connect to this port
    compression:
        enabled: false # Whether to enable compression or not; Set this to 'true' if this is a remote node, and you need to conserve outbound traffic
    # You will likely want to set this as high as your system can handle without issues if you use localtracks
    undertow:
        threads:
            io: 32       # CPU_COUNT * 2 i.e 32 for 16 core cpu
            worker: 128  # CPU_COUNT * 8 i.e 128 for 16 core cpu
spring:
    mvc:
        async:
            request-timeout: -1  #  Disable timeout
metrics:
    prometheus:
        enabled: false
        endpoint: /metrics
logging:
    file:
        path: ./logs/
    level:
        lavalink: INFO
        root: INFO
    request:
        enabled: true
        includeClientInfo: true
        includeHeaders: false
        includeQueryString: true
        includePayload: true
        maxPayloadLength: 10000
    logback:
        rollingpolicy:
            max-file-size: 25MB
            max-history: 7
            total-size-cap: 1GB
