lavalink:
    plugins:
    -   dependency: com.github.TopiSenpai.LavaSrc:lavasrc-plugin:a0a5a35
        repository: https://jitpack.io
    -   dependency: com.dunctebot:skybot-lavalink-plugin:1.4.1
        repository: https://m2.duncte123.dev/releases
    -   dependency: com.github.topisenpai:sponsorblock-plugin:1.0.5
        repository: https://jitpack.io
    -   dependency: me.rohank05:lavalink-filter-plugin:0.0.1
        repository: https://jitpack.io
    -   dependency: com.github.esmBot:lava-xm-plugin:v0.2.1
        repository: https://jitpack.io
    server:
        bufferDurationMs: 400
        filters:
            channelMix: true
            distortion: true
            echo: true
            equalizer: true
            karaoke: true
            lowPass: true
            rotation: true
            timescale: true
            tremolo: true
            vibrato: true
            volume: true
        frameBufferDurationMs: 1000
        gc-warnings: true
        opusEncodingQuality: 10
        password: CHANGE_ME
        playerUpdateInterval: 30
        resamplingQuality: HIGH
        soundcloudSearchEnabled: true
        sources:
            bandcamp: true
            http: true
            local: true
            soundcloud: true
            twitch: true
            vimeo: true
            youtube: true
        trackStuckThresholdMs: 10000
        useSeekGhosting: true
        youtubePlaylistLoadLimit: 100
        youtubeSearchEnabled: true
logging:
    file:
        path: ./logs/
    level:
        lavalink: INFO
        root: INFO
    logback:
        rollingpolicy:
            max-file-size: 25MB
            max-history: 7
            total-size-cap: 1GB
    request:
        enabled: true
        includeClientInfo: true
        includeHeaders: false
        includePayload: true
        includeQueryString: true
        maxPayloadLength: 10000
metrics:
    prometheus:
        enabled: false
        endpoint: /metrics
plugins:
    dunctebot:
        sources:
            clypit: true
            getyarn: true
            mixcloud: true
            ocremix: true
            pornhub: true
            reddit: true
            soundgasm: true
            tiktok: true
            tts: true
        ttsLanguage: en-US
    lavasrc:
        providers:
        -   dzisrc:%ISRC%
        -   ytmsearch:"%ISRC%"
        -   ytsearch:"%ISRC%"
        -   ytmsearch:%QUERY%
        -   ytsearch:%QUERY%
        -   dzsearch:%QUERY%
        -   scsearch:%QUERY%
        sources:
            applemusic: true
            deezer: true # requires a master decryption key
            spotify: true # requires a client id and secret
            yandexmusic: false
        applemusic:
            countryCode: US # the country code you want to use for filtering the artists top tracks and language. See https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
        deezer:
            masterDecryptionKey: CHANGE_ME
        spotify:
            clientId: CHANGE_ME
            clientSecret: CHANGE_ME
            countryCode: US # the country code you want to use for filtering the artists top tracks. See https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
        yandexmusic:
            accessToken: CHANGE_ME # the token used for accessing the yandex music api. See https://github.com/TopiSenpai/LavaSrc#yandex-music
sentry:
    dsn: ''
    environment: ''
    tags:
        pylav-version: 1.0.0
server:
    address: localhost
    port: 2155
